#pragma once
// Note fonts with extended Unicode coverage (generated by tools/genfont.py).

#include "../board.h"

extern const lgfx::GFXfont ObSans9;
extern const lgfx::GFXfont ObSansBold9;
extern const lgfx::GFXfont ObSansOblique9;
extern const lgfx::GFXfont ObSansBoldOblique9;
extern const lgfx::GFXfont ObMono9;
extern const lgfx::GFXfont ObSansBold12;
extern const lgfx::GFXfont ObSansBold18;
