#!/usr/bin/env python3
"""Generate LovyanGFX GFXfont headers with extended Unicode coverage.

Renders TrueType fonts the same way Adafruit's fontconvert does (1-bit, 141 DPI), so
the results match the stock FreeSans/FreeMono GFX fonts, but adds accented Latin,
Greek, Cyrillic, typographic punctuation and common symbols as sparse Unicode ranges.

Needs freetype-py.  Usage:  tools/genfont.py   (writes src/fonts/*.h)
"""
import os
import freetype

DPI = 141
FONT_DIR = "/usr/share/fonts/truetype/freefont"
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "fonts")

# (C name, TTF file, point size)
FONTS = [
    ("ObSans9", "FreeSans.ttf", 9),
    ("ObSansBold9", "FreeSansBold.ttf", 9),
    ("ObSansOblique9", "FreeSansOblique.ttf", 9),
    ("ObSansBoldOblique9", "FreeSansBoldOblique.ttf", 9),
    ("ObMono9", "FreeMono.ttf", 9),
    ("ObSansBold12", "FreeSansBold.ttf", 12),
    ("ObSansBold18", "FreeSansBold.ttf", 18),
]

RANGES = [
    (0x20, 0x7E),      # ASCII
    (0xA0, 0x17F),     # Latin-1 Supplement + Latin Extended-A
    (0x391, 0x3C9),    # Greek
    (0x401, 0x45F),    # Cyrillic
    (0x2010, 0x2027),  # dashes, quotes, bullet, ellipsis
    (0x2030, 0x203A),  # per mille, primes, angle quotes
    (0x20AC, 0x20AC),  # euro
    (0x2122, 0x2122),  # trade mark
    (0x2190, 0x2195),  # arrows
    (0x2212, 0x2212),  # minus
    (0x221E, 0x221E),  # infinity
    (0x2248, 0x2248),  # almost equal
    (0x2260, 0x2265),  # not equal, less/greater or equal
    (0x2713, 0x2717),  # check marks / crosses
]


def render(name, ttf, size):
    face = freetype.Face(os.path.join(FONT_DIR, ttf))
    face.set_char_size(size * 64, 0, DPI, 0)
    codes = [c for lo, hi in RANGES for c in range(lo, hi + 1)
             if c < 0x80 or face.get_char_index(c)]  # skip glyphs the font lacks
    bitmap = bytearray()
    glyphs = []
    for c in codes:
        face.load_char(c, freetype.FT_LOAD_TARGET_MONO | freetype.FT_LOAD_RENDER)
        g = face.glyph
        bm = g.bitmap
        offset = len(bitmap)
        acc, nbits = 0, 0
        for y in range(bm.rows):
            for x in range(bm.width):
                bit = (bm.buffer[y * bm.pitch + x // 8] >> (7 - x % 8)) & 1
                acc = (acc << 1) | bit
                nbits += 1
                if nbits == 8:
                    bitmap.append(acc)
                    acc, nbits = 0, 0
        if nbits:
            bitmap.append(acc << (8 - nbits))
        glyphs.append((c, offset, bm.width, bm.rows, g.advance.x >> 6, g.bitmap_left, 1 - g.bitmap_top))

    # Merge consecutive code points into EncodeRanges (base = index of the range's first glyph)
    ranges = []
    for i, (c, *_rest) in enumerate(glyphs):
        if ranges and ranges[-1][1] == c - 1:
            ranges[-1][1] = c
        else:
            ranges.append([c, c, i])

    y_adv = face.size.height >> 6
    out = [f"// Generated by tools/genfont.py from GNU FreeFont {ttf} at {size} pt ({DPI} dpi).",
           "// GNU FreeFont is GPLv3 with the font exception.", "#pragma once", "",
           f"static const uint8_t {name}Bitmaps[] PROGMEM = {{"]
    for i in range(0, len(bitmap), 16):
        out.append("  " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 16]) + ",")
    out.append("};")
    out.append("")
    out.append(f"static const lgfx::GFXglyph {name}Glyphs[] PROGMEM = {{")
    for c, off, w, h, adv, xo, yo in glyphs:
        out.append(f"  {{{off}, {w}, {h}, {adv}, {xo}, {yo}}},  // U+{c:04X}")
    out.append("};")
    out.append("")
    out.append(f"static lgfx::EncodeRange {name}Ranges[] = {{")
    for lo, hi, base in ranges:
        out.append(f"  {{0x{lo:04X}, 0x{hi:04X}, {base}}},")
    out.append("};")
    out.append("")
    out.append(f"const lgfx::GFXfont {name}((uint8_t*){name}Bitmaps, (lgfx::GFXglyph*){name}Glyphs, "
               f"0x{glyphs[0][0]:04X}, 0x{glyphs[-1][0]:04X}, {y_adv}, {len(ranges)}, {name}Ranges);")
    with open(os.path.join(OUT_DIR, name + ".h"), "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"{name}: {len(glyphs)} glyphs, {len(ranges)} ranges, {len(bitmap)} bitmap bytes")


if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    for args in FONTS:
        render(*args)
